---
layout: cv
title: Mason McDonough
---
Mason McDonough
Rexburg, ID 83440 masonmcdonough23@gmail.com +1 208 807 7731
Authorized to work in the US for any employer
Work Experience
 
Lifetime Product Installer
DJ Assembly-Hillsboro, OR
July 2025 to Present
We installed Lifetime products at peoples homes around the Treasure Valley mostly being sheds and playgrounds that we assembled.
Data Entry
Jeff McDonough CPA-Meridian, ID
January 2025 to April 2025
I did data entry for an accounting firm during tax season. I learned the basics of accounting and got a grasp on money and taxes.
Full Time Missionary (Volunteer)
The Church of Jesus Christ of Latter-day Saints-Iloilo, Philippines August 2022 to August 2024
I served a full time mission for The Church of Jesus Christ of Latter-Day Saints. I helped bring people to the Church and helped them in all sorts of ways. I learned a new language in the Philippines and learned their culture. I served others full time in order to help them voluntarily.

Education
 
Accounting (Some College)
BYU-I-Rexburg, ID
September 2024 to Present
High school diploma or GED
Skills
 
Some of my skills I have obtained are, Outdoor work, Heavy lifting, Excel data analysis, Microsoft Excel, Food safety management, Accounts receivable, Accounting and finance experience, Hand tools, Janitorial experience, Food safety, Computer skills, Accounting software, Accounts payable, Food service (1 year), and Bookkeeping
